### ISSUE TITLE
Problems with web3

### ISSUE THREAD

**Issue by xavik0f2** [MannyGrewal/BlockchainWithDynamics365#1]
When I compile the project I have a problem with the web3 package.

```
Debugger listening on [::]:5858
webpack-internal:///332:21
var _web = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"web3\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                                  ^

Error: Cannot find module "web3"
    at webpackMissingModule (webpack-internal:///332:21:76)
    at eval (webpack-internal:///332:21:157)
    at Object.<anonymous> (C:\Users\myuser\Documents\GIT\ISC\BlockchainWithDynamics365\Manny.Blockchain.ShoppingCart\public\bundle.js:3994:1)
    at __webpack_require__ (C:\Users\myuser\Documents\GIT\ISC\BlockchainWithDynamics365\Manny.Blockchain.ShoppingCart\public\bundle.js:20:30)
    at eval (webpack-internal:///331:15:20)
    at Object.<anonymous> (C:\Users\myuser\Documents\GIT\ISC\BlockchainWithDynamics365\Manny.Blockchain.ShoppingCart\public\bundle.js:3982:1)
    at __webpack_require__ (C:\Users\myuser\Documents\GIT\ISC\BlockchainWithDynamics365\Manny.Blockchain.ShoppingCart\public\bundle.js:20:30)
    at eval (webpack-internal:///330:15:21)
    at Object.<anonymous> (C:\Users\myuser\Documents\GIT\ISC\BlockchainWithDynamics365\Manny.Blockchain.ShoppingCart\public\bundle.js:3970:1)
    at __webpack_require__ (C:\Users\myuser\Documents\GIT\ISC\BlockchainWithDynamics365\Manny.Blockchain.ShoppingCart\public\bundle.js:20:30)
Press any key to continue...
```

Could you please help me?? Thank you in advance.

**Comment by MannyGrewal** [comment]
You need to install the web3 module in your local package repository
